// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Florian Bruniaux <florian@bruniaux.com>

"use client";

import { useEffect, useState } from "react";
import NextImage from "next/image";
import { Modal } from "@/components/modal";
import { StatsList } from "@/components/stats-list";
import type { GeoVelocityItem } from "@/app/api/stats/[owner]/[repo]/geo-velocity/route";
import type { RepoStats } from "@/app/api/stats/[owner]/[repo]/route";

type StatsModalProps = {
  open: boolean;
  onClose: () => void;
  owner: string;
  repo: string;
  displayStats: RepoStats;
  starsThisMonth: number;
  contributorsCount?: number | null;
  repoStars?: number;
  /**
   * Engaged-community points carry no location or company, so every location-derived
   * aggregate would render a hard 0. Hiding reads as a limitation; a 0 reads as a bug.
   */
  hideLocationAggregates?: boolean;
};

const ALL_TABS = ["top", "countries", "cities", "companies", "power", "rising"] as const;
const TABS_WITHOUT_LOCATION = ["top", "power", "rising"] as const;

export const StatsModal = ({ open, onClose, owner, repo, displayStats, starsThisMonth, contributorsCount, repoStars, hideLocationAggregates = false }: StatsModalProps) => {
  const [statsTab, setStatsTab] = useState<"countries" | "cities" | "top" | "companies" | "power" | "rising">("top");
  const [geoVelocity, setGeoVelocity] = useState<GeoVelocityItem[] | null>(null);
  const [geoVelocityLoading, setGeoVelocityLoading] = useState(false);
  const [statsFilter, setStatsFilter] = useState("");
  const [statsTopSort, setStatsTopSort] = useState<"followers" | "repos">("followers");

  // Lazy-fetch geo velocity when user opens the Rising tab
  useEffect(() => {
    if (!open || statsTab !== "rising" || geoVelocity !== null || geoVelocityLoading) return;
    const ac = new AbortController();
    setGeoVelocityLoading(true);
    fetch(`/api/stats/${owner}/${repo}/geo-velocity`, { signal: ac.signal })
      .then((r) => r.ok ? r.json() : null)
      .then((data: { items: GeoVelocityItem[] } | null) => {
        if (data) setGeoVelocity(data.items);
      })
      .catch(() => {})
      .finally(() => setGeoVelocityLoading(false));
    return () => ac.abort();
  }, [open, statsTab, geoVelocity, geoVelocityLoading, owner, repo]);

  return (
    <Modal open={open} onClose={onClose} maxWidth="max-w-5xl" innerClassName="flex flex-col max-h-[85vh]">
      {/* Header */}
      <div className="flex items-center justify-between px-5 py-4 border-b border-border-subtle flex-shrink-0">
        <h2 className="text-foreground font-semibold text-sm">Stargazer Stats</h2>
        <div className="flex items-center gap-2">
          <button
            onClick={() => {
              const md = [
                `# ${owner}/${repo} on StarMapper`,
                ``,
                `- **Total stargazers**: ${(repoStars ?? displayStats.totalStars).toLocaleString()} (${displayStats.mappingRate}% mapped)`,
                ...(hideLocationAggregates ? [] : [
                  `- **Countries**: ${displayStats.countryCount}`,
                  `- **Cities**: ${displayStats.topCities.length}`,
                ]),
                `- **Avg followers**: ${displayStats.avgFollowers.toLocaleString()}`,
                ``,
                ...(hideLocationAggregates ? [] : [
                  `## Top Countries`,
                  ...displayStats.topCountries.slice(0, 10).map(([c, n], i) => `${i + 1}. ${c}: ${n}`),
                  ``,
                  `## Top Cities`,
                  ...displayStats.topCities.slice(0, 10).map(([c, n], i) => `${i + 1}. ${c}: ${n}`),
                  `## Top Companies`,
                  ...(displayStats.topCompanies.length ? displayStats.topCompanies.slice(0, 10).map(([c, n], i) => `${i + 1}. ${c}: ${n}`) : ["No company data"]),
                  ``,
                ]),
                `## Top Stargazers`,
                ...displayStats.topUsers.slice(0, 10).map((u, i) => `${i + 1}. [@${u.login}](https://github.com/${u.login}) (${u.followers.toLocaleString()} followers)`),
                ``,
                `*Generated by [StarMapper](${process.env.NEXT_PUBLIC_APP_URL ?? "https://starmapper.bruniaux.com"})*`,
              ].join("\n");
              navigator.clipboard.writeText(md).catch(() => {});
            }}
            className="flex items-center gap-1.5 text-xs text-muted hover:text-foreground bg-surface-alt hover:bg-border border border-border rounded-lg px-2.5 py-1 transition-colors"
            title="Copy stats as Markdown"
          >
            <svg width="12" height="12" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true">
              <path d="M0 6.75C0 5.784.784 5 1.75 5h1.5a.75.75 0 0 1 0 1.5h-1.5a.25.25 0 0 0-.25.25v7.5c0 .138.112.25.25.25h7.5a.25.25 0 0 0 .25-.25v-1.5a.75.75 0 0 1 1.5 0v1.5A1.75 1.75 0 0 1 9.25 16h-7.5A1.75 1.75 0 0 1 0 14.25Z"/><path d="M5 1.75C5 .784 5.784 0 6.75 0h7.5C15.216 0 16 .784 16 1.75v7.5A1.75 1.75 0 0 1 14.25 11h-7.5A1.75 1.75 0 0 1 5 9.25Zm1.75-.25a.25.25 0 0 0-.25.25v7.5c0 .138.112.25.25.25h7.5a.25.25 0 0 0 .25-.25v-7.5a.25.25 0 0 0-.25-.25Z"/>
            </svg>
            Copy MD
          </button>
          <button onClick={onClose} aria-label="Close stats" className="text-muted hover:text-foreground text-lg leading-none"><span aria-hidden="true">✕</span></button>
        </div>
      </div>

      {/* Body: 2-column layout */}
      <div className="flex flex-1 min-h-0">

        {/* Left pane: summary cards + notables */}
        <div className="w-72 flex-shrink-0 border-r border-border-subtle flex flex-col overflow-y-auto">
          {/* Summary cards — 2-col grid */}
          <div className="grid grid-cols-2 gap-2 px-4 py-4">
            <div className="bg-background rounded-lg px-2 py-2 text-center">
              <div className="text-xl font-bold text-foreground">
                {(() => { const s = repoStars ?? displayStats.totalStars; return s >= 1000 ? `${(s / 1000).toFixed(1)}k` : s; })()}
              </div>
              <div className="text-2xs text-muted uppercase tracking-wide mt-0.5">stars</div>
              {starsThisMonth > 0 && (
                <div className="text-2xs text-accent-green mt-0.5">+{starsThisMonth >= 1000 ? `${(starsThisMonth / 1000).toFixed(1)}k` : starsThisMonth}/mo</div>
              )}
            </div>
            <div className="bg-background rounded-lg px-2 py-2 text-center">
              <div className="text-xl font-bold text-accent-green">{displayStats.mappingRate}%</div>
              <div className="text-2xs text-muted uppercase tracking-wide mt-0.5">mapped</div>
            </div>
            {!hideLocationAggregates && (
              <>
                <div className="bg-background rounded-lg px-2 py-2 text-center">
                  <div className="text-xl font-bold text-foreground">{displayStats.countryCount}</div>
                  <div className="text-2xs text-muted uppercase tracking-wide mt-0.5">countries</div>
                </div>
                <div className="bg-background rounded-lg px-2 py-2 text-center">
                  <div className="text-xl font-bold text-foreground">{displayStats.topCities.length}</div>
                  <div className="text-2xs text-muted uppercase tracking-wide mt-0.5">cities</div>
                </div>
              </>
            )}
            <div className="bg-background rounded-lg px-2 py-2 text-center">
              <div className="text-xl font-bold text-accent-orange">
                {displayStats.avgFollowers >= 1000 ? `${(displayStats.avgFollowers / 1000).toFixed(1)}k` : displayStats.avgFollowers}
              </div>
              <div className="text-2xs text-muted uppercase tracking-wide mt-0.5">avg flw</div>
            </div>
            <div className="bg-background rounded-lg px-2 py-2 text-center">
              {(() => {
                const { botCount, enrichedUserCount } = displayStats;
                const pct = enrichedUserCount > 0 ? Math.round((botCount / enrichedUserCount) * 100) : null;
                return (
                  <>
                    <div className={`text-xl font-bold ${pct !== null && pct > 20 ? "text-accent-red" : "text-muted"}`}>
                      {pct !== null ? `${pct}%` : "—"}
                    </div>
                    <div className="text-2xs text-muted uppercase tracking-wide mt-0.5">suspect</div>
                  </>
                );
              })()}
            </div>
            <div className="col-span-2 bg-background rounded-lg px-2 py-2 text-center">
              <div className="text-xl font-bold text-foreground">
                {contributorsCount != null
                  ? contributorsCount >= 1000
                    ? `${(contributorsCount / 1000).toFixed(1)}k`
                    : contributorsCount
                  : "—"}
              </div>
              <div className="text-2xs text-muted uppercase tracking-wide mt-0.5">contributors</div>
            </div>
          </div>

          {/* Notables — vertical list */}
          {displayStats.topUsers.length > 0 && (
            <div className="border-t border-border-subtle px-4 py-3 flex flex-col flex-1">
              <div className="flex items-center justify-between mb-2.5">
                <span className="text-2xs text-muted uppercase tracking-wide">Notables</span>
                <button
                  onClick={() => { setStatsTab("top"); setStatsFilter(""); }}
                  className="text-2xs text-accent-blue hover:underline"
                >
                  Top {displayStats.topUsers.length} →
                </button>
              </div>
              <div className="space-y-2">
                {displayStats.topUsers.slice(0, 10).map((u) => (
                  <a
                    key={u.login}
                    href={`/profile/${encodeURIComponent(u.login)}`}
                    title={`@${u.login} (${u.followers.toLocaleString()} followers)`}
                    aria-label={`@${u.login}, ${u.followers.toLocaleString()} followers`}
                    className="flex items-center gap-2 hover:opacity-75 transition-opacity"
                  >
                    {u.avatarUrl
                      ? <NextImage src={u.avatarUrl} alt="" width={24} height={24} sizes="24px" className="w-6 h-6 rounded-full ring-1 ring-border flex-shrink-0" unoptimized />
                      : <div className="w-6 h-6 rounded-full bg-surface-alt ring-1 ring-border flex-shrink-0" />
                    }
                    <div className="flex-1 min-w-0">
                      <div className="text-xs text-accent-blue truncate">@{u.login}</div>
                      {u.name && u.name !== u.login && (
                        <div className="text-2xs text-muted-subtle truncate">{u.name}</div>
                      )}
                    </div>
                    <span className="text-2xs text-muted tabular-nums flex-shrink-0">
                      {u.followers >= 1000 ? `${(u.followers / 1000).toFixed(1)}k` : u.followers}
                    </span>
                  </a>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Right pane: tabs + content */}
        <div className="flex-1 flex flex-col min-h-0 min-w-0">
          {/* Tabs */}
          <div role="tablist" aria-label="Stats view" className="flex border-b border-border-subtle flex-shrink-0">
            {(hideLocationAggregates ? TABS_WITHOUT_LOCATION : ALL_TABS).map((tab, idx, arr) => (
              <button
                key={tab}
                role="tab"
                id={`stats-tab-${tab}`}
                aria-selected={statsTab === tab}
                aria-controls={`stats-panel-${tab}`}
                tabIndex={statsTab === tab ? 0 : -1}
                onClick={() => { setStatsTab(tab); setStatsFilter(""); }}
                onKeyDown={(e) => {
                  if (e.key === "ArrowRight") { const next = arr[(idx + 1) % arr.length]; setStatsTab(next); setStatsFilter(""); }
                  if (e.key === "ArrowLeft") { const prev = arr[(idx - 1 + arr.length) % arr.length]; setStatsTab(prev); setStatsFilter(""); }
                }}
                className={`flex-1 py-2.5 text-xs font-medium transition-colors ${
                  statsTab === tab
                    ? "text-accent-blue border-b-2 border-accent-blue -mb-px"
                    : "text-muted hover:text-foreground"
                }`}
              >
                {tab === "top" ? "Top Stars" : tab === "countries" ? "Countries" : tab === "cities" ? "Cities" : tab === "companies" ? "Companies" : tab === "power" ? <><span aria-hidden="true">⚡</span> Power</> : <><span aria-hidden="true">📈</span> Rising</>}
              </button>
            ))}
          </div>

          {/* Filter input for countries/cities/companies */}
          {(statsTab === "countries" || statsTab === "cities" || statsTab === "companies") && (
            <div className="px-5 pt-3 flex-shrink-0">
              <input
                value={statsFilter}
                onChange={(e) => setStatsFilter(e.target.value)}
                placeholder={`Filter ${statsTab}…`}
                aria-label={`Filter ${statsTab}`}
                className="w-full bg-background border border-border rounded-lg px-3 py-1.5 text-xs text-foreground placeholder-muted-subtle focus:outline-none focus:border-accent-blue"
              />
            </div>
          )}

          {/* List — tabpanel */}
          <div
            role="tabpanel"
            id={`stats-panel-${statsTab}`}
            aria-labelledby={`stats-tab-${statsTab}`}
            className="overflow-y-auto flex-1 px-5 py-3"
          >
            {statsTab === "top" && (
              <div>
                {/* Sort toggle */}
                <div className="flex items-center gap-1 mb-3">
                  <span id="stats-sort-label" className="text-muted-subtle text-2xs uppercase tracking-wide mr-1">Sort:</span>
                  <div role="radiogroup" aria-labelledby="stats-sort-label" className="flex gap-1">
                    {(["followers", "repos"] as const).map((s) => (
                      <button
                        key={s}
                        role="radio"
                        aria-checked={statsTopSort === s}
                        onClick={() => setStatsTopSort(s)}
                        className={`px-2 py-0.5 rounded text-2xs font-medium transition-colors ${
                          statsTopSort === s
                            ? "bg-accent-blue/20 text-accent-blue"
                            : "text-muted hover:text-foreground"
                        }`}
                      >
                        {s === "followers" ? "Followers" : "Public repos"}
                      </button>
                    ))}
                  </div>
                </div>
                <div className="space-y-2.5">
                  {[...displayStats.topUsers]
                    .sort((a, b) => statsTopSort === "followers" ? b.followers - a.followers : b.publicRepos - a.publicRepos)
                    .map((u, i) => (
                    <div key={u.login} className="flex items-center gap-3 py-0.5">
                      <span className="text-muted-subtle text-xs w-5 text-right flex-shrink-0">{i + 1}</span>
                      {u.avatarUrl
                        ? <NextImage src={u.avatarUrl} alt="" width={32} height={32} sizes="32px" className="w-8 h-8 rounded-full flex-shrink-0 ring-1 ring-border" unoptimized />
                        : <div className="w-8 h-8 rounded-full bg-surface-alt flex-shrink-0 ring-1 ring-border" />
                      }
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-1.5 flex-wrap">
                          <a
                            href={`/profile/${encodeURIComponent(u.login)}`}
                            className="text-accent-blue text-xs font-medium hover:underline"
                          >
                            @{u.login}
                          </a>
                          {u.company && (
                            <span className="text-2xs text-muted bg-surface-alt border border-border-subtle rounded px-1.5 py-px truncate max-w-24">
                              {u.company.replace(/^@/, "")}
                            </span>
                          )}
                        </div>
                        {u.name && u.name !== u.login && (
                          <div className="text-muted-subtle text-2xs truncate">{u.name}</div>
                        )}
                        {!u.name && u.location && (
                          <div className="text-muted-subtle text-2xs truncate">{u.location}</div>
                        )}
                      </div>
                      {statsTopSort === "repos" && u.publicRepos > 0 ? (
                        <a
                          href={`https://github.com/${u.login}?tab=repositories`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-accent-blue text-xs flex-shrink-0 tabular-nums hover:underline"
                          title="View public repos"
                        >
                          <svg width="11" height="11" viewBox="0 0 16 16" fill="currentColor" className="inline mr-1 mb-0.5"><path d="M2 2.5A2.5 2.5 0 0 1 4.5 0h8.75a.75.75 0 0 1 .75.75v12.5a.75.75 0 0 1-.75.75h-2.5a.75.75 0 0 1 0-1.5h1.75v-2h-8a1 1 0 0 0-.714 1.7.75.75 0 1 1-1.072 1.05A2.495 2.495 0 0 1 2 11.5Zm10.5-1h-8a1 1 0 0 0-1 1v6.708A2.486 2.486 0 0 1 4.5 9h8Z"/></svg>
                          {u.publicRepos.toLocaleString()}
                        </a>
                      ) : (
                        <span className="text-muted text-xs flex-shrink-0 tabular-nums">
                          <svg width="11" height="11" viewBox="0 0 16 16" fill="currentColor" className="inline mr-1 mb-0.5 text-muted"><path d="M3 8a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm3 0a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm3 0a1 1 0 1 1 0-2 1 1 0 0 1 0 2ZM1.5 3A1.5 1.5 0 0 0 0 4.5v7A1.5 1.5 0 0 0 1.5 13h13a1.5 1.5 0 0 0 1.5-1.5v-7A1.5 1.5 0 0 0 14.5 3Z"/></svg>
                          {u.followers.toLocaleString()}
                        </span>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}
            {statsTab === "countries" && (
              <StatsList
                items={displayStats.topCountries.filter(([name]) => !statsFilter || name.toLowerCase().includes(statsFilter.toLowerCase()))}
                max={displayStats.topCountries[0]?.[1] ?? 1}
              />
            )}
            {statsTab === "cities" && (
              <StatsList
                items={displayStats.topCities.filter(([name]) => !statsFilter || name.toLowerCase().includes(statsFilter.toLowerCase()))}
                max={displayStats.topCities[0]?.[1] ?? 1}
              />
            )}
            {statsTab === "companies" && (
              <div className="space-y-2">
                {displayStats.topCompanies
                  .filter(([company]) => !statsFilter || company.toLowerCase().includes(statsFilter.toLowerCase()))
                  .map(([company, count], idx) => (
                  <div key={company} className="flex items-center gap-3">
                    <div className="text-muted-subtle text-xs w-4 text-right flex-shrink-0">{idx + 1}</div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-foreground text-xs truncate">{company}</span>
                        <span className="text-muted text-xs ml-2 flex-shrink-0">{count}</span>
                      </div>
                      <div className="h-1 bg-surface-alt rounded-full">
                        <div className="h-1 bg-accent-blue rounded-full" style={{ width: `${(count / (displayStats.topCompanies[0]?.[1] ?? 1)) * 100}%` }} />
                      </div>
                    </div>
                  </div>
                ))}
                {displayStats.topCompanies.length === 0 && (
                  <div className="text-center text-muted-subtle text-xs py-8">No company data available</div>
                )}
              </div>
            )}
            {statsTab === "rising" && (
              <div>
                {geoVelocityLoading && (
                  <div className="text-center text-muted-subtle text-xs py-8">Loading…</div>
                )}
                {!geoVelocityLoading && geoVelocity !== null && geoVelocity.length === 0 && (
                  <div className="text-center text-muted-subtle text-xs py-8">
                    <div className="text-2xl mb-2" aria-hidden="true">📈</div>
                    <div>Not enough timestamp data yet.</div>
                    <div className="mt-1 text-2xs">Needs repos with starredAt data from the last 90 days.</div>
                  </div>
                )}
                {!geoVelocityLoading && geoVelocity !== null && geoVelocity.length > 0 && (
                  <div className="space-y-2.5">
                    <p className="text-2xs text-muted-subtle mb-3">
                      New stars in the last 30 days vs. the prior 60-day rate. Shows which countries are discovering this repo.
                    </p>
                    {geoVelocity.map((item) => {
                      const trendColor =
                        item.trend === "rising" ? "text-accent-green" :
                        item.trend === "new"     ? "text-accent-blue" :
                        item.trend === "declining" ? "text-accent-red" : "text-muted";
                      const trendLabel =
                        item.trend === "rising"   ? `↑ ${item.ratio}×` :
                        item.trend === "new"      ? "✦ new" :
                        item.trend === "declining" ? "↓ slowing" : "→ stable";
                      return (
                        <div key={item.country} className="flex items-center gap-3">
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-1.5 mb-0.5">
                              <span className="text-xs text-foreground font-medium truncate">{item.country}</span>
                              <span className={`text-2xs font-semibold flex-shrink-0 ${trendColor}`}>{trendLabel}</span>
                            </div>
                            <div className="flex items-center gap-1 text-2xs text-muted-subtle">
                              <span>{item.stars30d} this month</span>
                              <span>·</span>
                              <span>{item.total.toLocaleString()} total</span>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            )}
            {statsTab === "power" && (
              <div className="space-y-2.5">
                {displayStats.powerStargazers.length === 0 && (
                  <div className="text-center text-muted-subtle text-xs py-8">
                    <div className="text-2xl mb-2" aria-hidden="true">⚡</div>
                    <div>No power stargazers yet.</div>
                    <div className="mt-1 text-2xs">Appears after multiple repos are scanned.</div>
                  </div>
                )}
                {displayStats.powerStargazers.map((u, i) => (
                  <div key={u.login} className="flex items-center gap-3 py-0.5">
                    <span className="text-muted-subtle text-xs w-5 text-right flex-shrink-0">{i + 1}</span>
                    <NextImage src={u.avatarUrl} alt="" width={32} height={32} sizes="32px" className="w-8 h-8 rounded-full flex-shrink-0 ring-1 ring-border" unoptimized />
                    <div className="flex-1 min-w-0">
                      <a
                        href={`/profile/${encodeURIComponent(u.login)}`}
                        className="text-accent-blue text-xs font-medium hover:underline"
                      >
                        @{u.login}
                      </a>
                      {u.name && u.name !== u.login && (
                        <div className="text-muted-subtle text-2xs truncate">{u.name}</div>
                      )}
                    </div>
                    <span className="text-accent-orange text-xs flex-shrink-0 tabular-nums font-medium">
                      {u.trackedRepos} repos
                    </span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </Modal>
  );
};
